on: [push]

jobs:
  openfoam_job:
    runs-on: ubuntu-latest
    container: openfoamplus/of_v1906_centos73
    name: A job to test OpenFOAM
    steps:
    - name: Install tree
      id: tree
      run: yum install -y tree
    - name: Take a look
      id: look
      run: |
        tree -L 2
        cd data
        ls
        tree
    - name: Activate OpenFOAM
      id: activate
      run: |
        source /opt/OpenFOAM/setImage_v1906.sh
        blockMesh -help
    - name: Check activation
      id: check
      run: blockMesh -help