on: [push]

jobs:
  openfoam_job:
    runs-on: ubuntu-latest
    name: A job to test OpenFOAM
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
    - name: OpenFOAM action step
      id: openfoam
      uses: parallelwindfarms/docker-tests@develop
      run: blockMesh -help