on: [push]

jobs:
  openfoam_job:
    runs-on: ubuntu-latest
    container: openfoamplus/of_v1906_centos73
    name: A job to test OpenFOAM
    steps:
    - name: Install tree
      id: tree
      run: yum install -y tree
    - name: Test installation
      id: test
      run: cd data && ls && tree