on: [push]

jobs:
  openfoam_job:
    runs-on: ubuntu-latest
    name: A job to test OpenFOAM
    steps:
    - name: OpenFOAM action step
      id: openfoam
      uses: parallelwindfarms/docker-tests@develop
    - name: Install tree
      id: tree
      run: yum install -y tree
    - name: Test installation
      id: test
      run: cd data && ls && tree